name: mcemeurckart_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1
  device_info_plus: ^9.1.0
  document_file_save_plus: ^2.0.0
  file_picker: ^5.5.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_document_picker: ^5.2.3
  flutter_downloader: ^1.11.2
  flutter_native_splash: ^2.3.2
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  pdf: ^3.10.4
  permission_handler: ^11.0.0
  responsive_framework: ^1.1.0
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/icons/navigation-bar/
    - assets/icons/social-media/
    - assets/icons/others/
    - assets/images/
    - assets/images/delivery_screen/
    - assets/images/intro_screen/
    - assets/images/intro_screen/paralax-background/
    - assets/images/order_screen/
    - assets/images/product_screen/
    - assets/images/profile_screen/
    - assets/images/search_screen/
    - assets/images/wishlist_screen/
    - assets/images/wishlist_screen/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500

    #         style: italic
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-SemiBold.ttf
          weight: 600
