// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVirkKTdYVnUWgWSi1qqtLHPEZyyVJ_0o',
    appId: '1:1035718047234:web:f866594d14ef27d875591b',
    messagingSenderId: '1035718047234',
    projectId: 'mcemeurccart',
    authDomain: 'mcemeurccart.firebaseapp.com',
    storageBucket: 'mcemeurccart.appspot.com',
    measurementId: 'G-WEH1VS69B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyD2hSTOquuFA4Ks-46oAplmpz8hObl_U',
    appId: '1:1035718047234:android:24b57fe5b92695b475591b',
    messagingSenderId: '1035718047234',
    projectId: 'mcemeurccart',
    storageBucket: 'mcemeurccart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDME2taNkhiNUWLaD7ZbnFXG2ZRDNWuQMk',
    appId: '1:1035718047234:ios:c9e0a8669c58706b75591b',
    messagingSenderId: '1035718047234',
    projectId: 'mcemeurccart',
    storageBucket: 'mcemeurccart.appspot.com',
    iosClientId: '1035718047234-mp79opfjrg2bd7glor1q4i8d9phd0a2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcemeurckartAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDME2taNkhiNUWLaD7ZbnFXG2ZRDNWuQMk',
    appId: '1:1035718047234:ios:d22e424cf9b6ef8475591b',
    messagingSenderId: '1035718047234',
    projectId: 'mcemeurccart',
    storageBucket: 'mcemeurccart.appspot.com',
    iosClientId: '1035718047234-dni6956mork1ufcqbg0cuqm9pv8i998f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcemeurckartAdmin.RunnerTests',
  );
}
